### ISSUE TITLE
fft double precision

### ISSUE THREAD

**Issue by digego** [digego/extempore#103]
It would be nice if fft provided 'native' double precision support in addition to single precision floating point support.  I appreciate that this would mean doubling up in the kiss fft library but would be worth while as there is a fair additional cost in the double->float float->double translations.  Given we default to 'doubles' we should at the very least make double precision the non-translated option.

**Comment by benswift** [comment]
Closing this, since `SAMPLE` is a float now, it's probably not an issue.
