### ISSUE TITLE
newbie question: no INSTALL file?

### ISSUE THREAD

**Issue by plutek** [digego/extempore#152]
greetings! trying to compile extempore on linux here...

when i run all.bash, i get this error:
Missing config/llvm.bash file. See INSTALL.
...but there is no INSTALL file... what do i need to do before all.bash?

also, has anyone tried using llvm 3.6? do we still need a patched 3.4.2, or might this newer version be ok?

thanks much... cheers!
.pltk.

**Comment by benswift** [comment]
There's now an install file in master.  Woohoo!
