### ISSUE TITLE
is JACK no longer supported on linux?

### ISSUE THREAD

**Issue by giorashh** [digego/extempore#157]
Compilation triggers bad audio hiccups and I thought JACK might help
with. It looks like `./all.bash -DJACK_AUDIO` hasn't worked since cc999f3bf,
though the ifdef still exists in `config/linux.make`.

**Comment by Arseniusz** [comment]
Hello.

>you can still use a jack backend if you use (an appropriately configured) portaudio

Can you briefly explain how can I use extempore with Jack on GNU/Linux?

**Comment by digego** [comment]
via, portaudio.

You just need to make sure that portaudio builds with jack support.  I
don't think the cmake file currently does include jack support by default
(on linux), so this might deserve a new bug report (i.e. add jack build
support for portaudio to extempore cmake)

**Comment by Arseniusz** [comment]
Thanks for answer.
I didn't find any reference to jack2 in CMakeLists.txt so I'll make a bug report tomorrow.

P.s all night searching for good alternative for CommonMusic package and find your project. It's awesome.
