### ISSUE TITLE
Some linux distros do not provide unversioned .so file when installing libs

### ISSUE THREAD

**Issue by giorashh** [digego/extempore#165]
On fedora at least:
```sh
$ rpm -qlv cairo | grep -P 'lib64/lib\w+.so'
lrwxrwxrwx    1 root    root                       21 Aug 16 04:26 /usr/lib64/libcairo.so.2 -> libcairo.so.2.11301.0
-rwxr-xr-x    1 root    root                  1120536 Aug 16 04:27 /usr/lib64/libcairo.so.2.11301.0
 
$ rpm -qlv cairo-devel | grep -P 'lib64/lib\w+.so' 
lrwxrwxrwx    1 root    root                       21 Aug 16 04:26 /usr/lib64/libcairo.so -> libcairo.so.2.11301.0

$ rpm -qlv SOIL | grep -P 'lib64/lib\w+.so' 
lrwxrwxrwx    1 root    root                       24 Aug 15 23:36 /usr/lib64/libSOIL.so.1 -> libSOIL.so.1.07-20071110
-rwxr-xr-x    1 root    root                    94584 Aug 15 23:36 /usr/lib64/libSOIL.so.1.07-20071110
 
$ rpm -qlv SOIL-devel | grep -P 'lib64/lib\w+.so' 
lrwxrwxrwx    1 root    root                       24 Aug 15 23:36 /usr/lib64/libSOIL.so -> libSOIL.so.1.07-20071110
```

Reasonble to require that applications specify the major number of libs they depend on, yet
`libs/external` files ask simply for `libfoo.so` which isn't there unless the devel package has been installed. It may also break the next time a major version of the library is released (which is rare, granted).

I can submit a PR if it'll get merged.

**Comment by benswift** [comment]
This is largely resolved by two things:
1. `bind-dylib` now (optionally) takes a list, so we can specify multiple `.so` names, which will be tried in order (see `libs/external/glfw3.xtm` for an example)
2. we now package all the libs required for at least the `libs/external` directory on all platforms, so we know for sure what they'll be called
So I'll close this - let me know if you have any further thoughts.
