### ISSUE TITLE
Function calls do not check number of arguments

### ISSUE THREAD

**Issue by giorashh** [digego/extempore#171]
```scheme
(bind-func foo
  (lambda (x:i64)
	x)
  )
(foo 1) ; returns 1, ok.
(foo 1 2) ; returns 1, why no error?
```

Should have complained of no function with suitable signature.

**Comment by benswift** [comment]
This is an issue with the scheme wrapper for `foo`. If `(foo 1 2)` were wrapped in a call-as-xtlang form the error would be more helpful.  Still, I've made the scheme wrapper error message a bit more helpful.
