### ISSUE TITLE
Brew installation fails on compile-stdlib.sh

### ISSUE THREAD

**Issue by lambdamusic** [digego/extempore#176]
Hi guys - I'm on Yosemite and tried installing Extempore using brew but `compile-stdlib.sh` hangs forever (+1hr) so I had to stop it. 

Do I have to set manually the extempore-llvm flags? Or any idea what could be going wrong?

```
>brew list
assimp		emacs		lame		libvorbis	readline	swig
autoconf	flac		libogg		openssl		rtmidi-c	tomcat
automake	git		libsndfile	pcre		sdl		tree
boost		gmp		libsoil		pkg-config	shivavg		webkit2png
cmake		kissfft		libtool		portaudio	swi-prolog	xz

>brew outdated
emacs (24.3 < 24.4)

>brew install --with-stdlib extempore
==> Installing extempore from benswift/homebrew-extempore
==> Installing extempore dependency: extempore-llvm
==> Downloading http://llvm.org/releases/3.4.1/llvm-3.4.1.src.tar.gz
Already downloaded: /Library/Caches/Homebrew/extempore-llvm-3.4.1.tar.gz
==> Patching
patching file lib/AsmParser/LLParser.cpp
Hunk #1 succeeded at 1593 (offset 244 lines).
==> ./configure --prefix=/usr/local/Cellar/extempore-llvm/3.4.1 --enable-optimized --disable-bindings --enable-targets=host
==> make install
==> Caveats
This is a specifically patched version of LLVM for building Extempore.
It shouldn't get in the way of any other LLVM install.

If you have any problems, raise them on extemporelang@googlegroups.com

This formula is keg-only, which means it was not symlinked into /usr/local.

This is a specially patched LLVM for use in building Extempore.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/extempore-llvm/lib
    CPPFLAGS: -I/usr/local/opt/extempore-llvm/include

==> Summary
🍺  /usr/local/Cellar/extempore-llvm/3.4.1: 645 files, 112M, built in 7.2 minutes
==> Installing extempore
==> Downloading https://github.com/digego/extempore/archive/0.59.zip
Already downloaded: /Library/Caches/Homebrew/extempore-0.59.zip
==> ./all.bash
==> (pre)compiling the Extempore standard library.  This may take a few minutes...
==> ./compile-stdlib.sh
# this hangs indefinitely..
```

Thanks in advance for your help.

**Comment by digego** [comment]
Hey Michele,

Looks like extempore installed ok, so you should be able to run
compile-stdlib.sh standalone.  So ... can you do that for us, which should
dump much more info to the shell.

cd /usr/local/Cellar/extempore/0.59/
$ ./compile-stdlib.sh

let us know what you get ... we'll just need to tail of the shell output
(last 10 lines or so should suffice).

**Comment by lambdamusic** [comment]
Hi Andrew :-) 

strangely enough, there's no extempore folder. 

```
/usr/local/Cellar>ls | grep "extempore"
extempore-llvm
```

I will try installing extempore without stlib - just to see if that works.

**Comment by lambdamusic** [comment]
Here we go. Extempore installed and running ok - however the `stdlib` compilation fails after a minute or so:

```
[.....]
------------- Extempore -------------- 
Andrew Sorensen (c) 2010-2014
andrew@moso.com.au, @digego

ARCH           : x86_64-apple-darwin14.0.0
CPU            : 
ATTRS          : 
MCJIT          : NO
Output Device  : Built-in Output
Input Device   : 
SampleRate     : 44100
Channels Out   : 2
Channels In    : 0
Frames         : 128
Latency        : 0.0189342 sec
---------------------------------------

Starting utility process
Trying to connect to 'localhost' on port 7098
New Client Connection 
Successfully connected to remote process

Starting primary process
Trying to connect to 'localhost' on port 7099
New Client Connection 
Successfully connected to remote process

Evaluating expression: (sys:precomp:compile-xtm-file "libs/external/fft.xtm" #t #t #t)

Loading xtmstd library...
Loaded xtmstd library in 1.102948 seconds
sys:load notification std already loaded 
Loading xtmmath library...
Loaded xtmmath library in 6.757007 seconds
sys:load notification math already loaded 
Error: could not load  kiss_fft.dylib  dynamic library
"Could not load kiss_fft dynamic library"
```

**Comment by digego** [comment]
Hmm, no kiss fft lib installed so it looks like your brew install has gone awry in some way.

On 26 January 2015 7:34:03 pm AEST, Michele Pasin <notifications@github.com> wrote:
>Here we go. Extempore installed and running ok - however the `stdlib`
>compilation fails after a minute or so:
>
>```
>[.....]
>------------- Extempore -------------- 
>Andrew Sorensen (c) 2010-2014
>andrew@moso.com.au, @digego
>
>ARCH           : x86_64-apple-darwin14.0.0
>CPU            : 
>ATTRS          : 
>MCJIT          : NO
>Output Device  : Built-in Output
>Input Device   : 
>SampleRate     : 44100
>Channels Out   : 2
>Channels In    : 0
>Frames         : 128
>Latency        : 0.0189342 sec
>---------------------------------------
>
>Starting utility process
>Trying to connect to 'localhost' on port 7098
>New Client Connection 
>Successfully connected to remote process
>
>Starting primary process
>Trying to connect to 'localhost' on port 7099
>New Client Connection 
>Successfully connected to remote process
>
>Evaluating expression: (sys:precomp:compile-xtm-file
>"libs/external/fft.xtm" #t #t #t)
>
>Loading xtmstd library...
>Loaded xtmstd library in 1.102948 seconds
>sys:load notification std already loaded 
>Loading xtmmath library...
>Loaded xtmmath library in 6.757007 seconds
>sys:load notification math already loaded 
>Error: could not load  kiss_fft.dylib  dynamic library
>"Could not load kiss_fft dynamic library"
>```
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/digego/extempore/issues/176#issuecomment-71434171

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by lambdamusic** [comment]
Yes - brew was indeed broken. BTW there's a thread in the mailing list about a similar problem (https://groups.google.com/forum/#!msg/extemporelang/dJgFf0-KRz4/hQXeD59dgZAJ). I'll follow up with comments there....

thanks a lot for the support.
