### ISSUE TITLE
Standard library build fails on OS X with: Compiler Error cannot find symbol  read_audio_data 

### ISSUE THREAD

**Issue by jamiebullock** [digego/extempore#177]
I installed extempore on OS X 10.10 following the instructions in the README.

When home-brew completes, I get the message:

```
It's a good idea to build the standard library at this point: you
can do this (in a shell) with:

> cd /usr/local/Cellar/extempore/0.59
> ./compile-stdlib.sh
```

Running `compile-stdlib.sh` eventually fails with:

```
sys:load notification audio_dsp already loaded 
sys:load notification std already loaded 
sys:load notification math already loaded 
sys:load notification audio_dsp already loaded 
Error: could not load  libsndfile.dylib  dynamic library
sys:load notification Error loading libsndfile dynamic library 
SetAlias:  cpxSAMPLE >>> cpxf
SetValue:  cpxSAMPLE_SIZE >>> i64
Compiler Error cannot find symbol  read_audio_data 
Error precompiling libs/external/audio_dsp_ext.xtm
```

I can get around this by symlinking libsndfile.dylib as libsndfile.0.dylib:

```
ln -s /usr/local/lib/libsndfile.0.dylib libsndfile.dylib
```

I guess this an upstream issue for your home-brew repository...

**Comment by benswift** [comment]
Hi Jamie

Thanks for the heads up.  Although it's a bit strange - I just did a
reinstall of the libsndfile formula (through homebrew) and it did put a
symlink to libsndfile.dylib in /usr/local/lib

What's the output of `brew doctor` on your box?

Cheers,
Ben

**Comment by benswift** [comment]
Hi Jamie

Sorry, I should have added that I'm on 10.10 as well.

Cheers,
Ben
