### ISSUE TITLE
segfault in make-envelope

### ISSUE THREAD

**Issue by gsingh93** [digego/extempore#179]
I was playing around with some of the standard library functions and I ended up writing this statement: 
`(println (apply (make-envelope '((1 1 1 1))) 1))`, which is incorrect. However, this statement causes a segfault, which shouldn't happen even if the statement is incorrect.

**Comment by benswift** [comment]
Hi Gulshan

I agree that this is bad.  Were you doing it in a bind-func (i.e. was it
Extempore code) or was it just in Scheme code

Handy reference: https://groups.google.com/forum/#!searchin/extemporelang/scheme$20xtlang/extemporelang/P1_-0zxTIUU/tUzfGY7lt9cJ

Cheers,
Ben

**Comment by gsingh93** [comment]
This was at the top level, so that would make it Scheme code I believe. And now that I think about it, it's especially strange that Scheme is crashing, not xtlang.

**Comment by digego** [comment]
I think that this is the same bug as #105
