### ISSUE TITLE
`Let` inside `while` test argument causes compiler error 

### ISSUE THREAD

**Issue by mrmagooey** [digego/extempore#189]
Compiling the following: 

    (bind-func func-name
      (lambda ()
        (while (let ((x 1)) #f)
          (println "nope"))))

Returns

    LLVM IR: <string>:38:1: error: multiple definition of local value named 'xPtr'
    %xPtr = alloca i64
    ^
    Compiler Error  compiler failed

**Comment by skintuna** [comment]
UNSUBSCRIBE

On Sunday, 8 November 2015, mrmagooey <notifications@github.com> wrote:

> The following:
>
> (bind-func func-name
>   (lambda ()
>     (while (let ((x 1)) #f)
>       (println "nope"))))
>
> Returns
>
> LLVM IR: <string>:38:1: error: multiple definition of local value named 'xPtr'
> %xPtr = alloca i64
> ^
> Compiler Error  compiler failed
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/digego/extempore/issues/189>.
>


-- 
Sent from Gmail Mobile

**Comment by digego** [comment]
fixed in head
