### ISSUE TITLE
Single branch `if` expression bug

### ISSUE THREAD

**Issue by mrmagooey** [digego/extempore#190]
Single branch if expressions (i.e. just the `then` branch, no `else` branch) will always execute the `then` branch regardless of what the `if-expr` evaluates to when they are the last sexp in a function.

    (bind-func if-statement1
      (lambda ()
        (if 0 (println "this should not print"))))
    
    (if-statement1)
    >> "this should not print"
    
    ;; simply making sure they are not the last sexp removes the behaviour
    (bind-func if-statement2:[void]*
      (lambda ()
        (if 0 (println "this should not print"))
        void))
    
    (if-statement2)
    >> 

I can't see any strange behaviour outside of this "final sexp" instance.

**Comment by digego** [comment]
Should now throw appropriate error message.
