### ISSUE TITLE
String pset!

### ISSUE THREAD

**Issue by mrmagooey** [digego/extempore#191]
Evaluating the following code:

    (call-as-xtlang (let ((str_ptr:i8* (zalloc 30)))
                  (pset! str_ptr 0 "a")))

Gives the error:
   
    Type Error calling pointer-set!, got i8*, was expecting i8* 

I'm not sure if the error is bad, if what I'm attempting to do is impossible, or some combination of both.

**Comment by digego** [comment]
This one looks partially correct to me.  We don't have any support for char literals at the moment - so "a" is i8* not i8.  So you are trying to set an i8* into an i8* - which is illegal.  I'm guessing what you meant was (call-as-xtlang (let ((str_ptr:i8* (zalloc 30))) (pset! str_ptr 0 97))) which sets an i8 into an i8*. 

However, I'm not sure why the error message is incorrect (i.e. should say got i8* was expecting i8).

**Comment by digego** [comment]
Fixed error message.
