### ISSUE TITLE
Truthyness inconsistency in `if` and `while`

### ISSUE THREAD

**Issue by mrmagooey** [digego/extempore#192]
`If` expressions will allow either (what I think of as C-style) integer `0` or `1`, or (scheme-style) `#f` or `#t` for truthyness in their eval-expr.

However, `while` loops only allow scheme-style `#f` and `#t` and will fail if using integers.

    (bind-func while1
      (lambda ()
        (while 0
          (println "this will not compile"))))
    
    (bind-func while2
      (lambda ()
        (while #f
          (println "this will compile"))))
    
    ;; this will compile
    (bind-func if1
      (lambda ()
        (if #f
            void
            void)))
    
    ;; this will compile
    (bind-func if2
      (lambda ()
        (if 0
            void
            void)))

I'm not sure which behaviour is the desired, but my two cents is that the `if` behaviour seems more useful.

**Comment by digego** [comment]
I've pushed a fix.  Close if happy
