### ISSUE TITLE
Can't return a tuple containing a vector 

### ISSUE THREAD

**Issue by mrmagooey** [digego/extempore#195]
Evaluating the following function

    (bind-func myfunc
      (lambda ()
        (let ((my_composite:</4,float/>* (zalloc)))
          my_composite)))

Gives:

    Type Error calling myfunc, got Type Error bad type [/4,float/]*

Adding additional values to the tuple, such as:

    (bind-func myfunc
      (lambda ()
        (let ((my_composite:<i32,/4,float/,|8,i32|,i32,i8>* (zalloc)))
          my_composite)))

Gives:

    Type Error calling myfunc, got Type Error bad type [i32,i32,i8,i8*,i8*]*

However, returning anything else from the function will allow it to compile, e.g.:

    (bind-func myfunc1
      (lambda ()
        (let ((my_composite:<i32,/4,float/,i8*>* (zalloc)))
          1)))

    (bind-func myfunc1
      (lambda ()
        (let ((my_composite:<i32,/4,float/,i8*>* (zalloc)))
          (cast my_composite i8*))))

**Comment by digego** [comment]
should now be fixed in head.
