### ISSUE TITLE
Libs core

### ISSUE THREAD

**Issue by mrmagooey** [digego/extempore#199]
There's a few files in the libs/core that are possibly not core extempore libraries, and might be better located elsewhere in the source tree. For example:

- tr-animation.xtm: This is only for emacs, and I'm pretty sure we've removed any animation from extempore-mode.el when it was moved to melpa.
- caas-server.xtm: This seems like a script rather than a library, as it doesn't expose any interface and does a single task.
- aot-compilation.xtm: This is a test file, but maybe it has to remain as an aot smoke test?
- game-of-life.xtm: This seems like a good example of extempore xtlang usage, but not really a general use library.
- wave-reader: This seems empty, but is being rewritten by @benswift I believe.
- math_ext-scm and math_ext could possibly be merged?

I would suggest that some portion of libs/core currently lives in runtime/scheme.xtm, e.g. xtmdoc.

**Comment by benswift** [comment]
> - tr-animation.xtm: This is only for emacs, and I'm pretty sure we've removed any animation from extempore-mode.el when it was moved to melpa.

Yep, we should get rid of this.

> - caas-server.xtm: This seems like a script rather than a library, as it doesn't expose any interface and does a single task.

Ditto.

> - aot-compilation.xtm: This is a test file, but maybe it has to remain as an aot smoke test?

That is the purpose, and it's useful to have around.  But we could move
it to contrib.

> - game-of-life.xtm: This seems like a good example of extempore xtlang usage, but not really a general use library.

Spot on.  Should go in contrib.

> - wave-reader: This seems empty, but is being rewritten by @benswift I believe.

Yeah, I moved this stuff the other day - now in
libs/core/audiobuffer.xtm

This can be deleted.

> - math_ext-scm and math_ext could possibly be merged?

Yep, we could include the macros with an impc:aot:do-or-emit

> I would suggest that some portion of libs/core currently lives in runtime/scheme.xtm, e.g. xtmdoc. 

Sure, I'll have a look.

Thanks Pete, these are good thoughts, and I think most of these changes
shouldn't cause any problems.

**Comment by digego** [comment]
Can we close this issue, and reopen a broader issue (or multiple issues) that covers the phone conversation?
