### ISSUE TITLE
Bind-poly fails silently if return type different

### ISSUE THREAD

**Issue by mrmagooey** [digego/extempore#201]
Whilst overloading the print function, I noticed that bind-poly seems to fail silently if I return anything other than a void (which is what every other print overload returns).

So the following test_print overload works fine

    (bind-type test-type1 <i32,i8*> "")
    
    (bind-func test_print:[void,test-type1*]*
      (lambda (x)
        (println "this will print")
        void))
    
    (bind-poly print test_print)
    
    (bind-func test-bad-print
      (lambda ()
        (let ((mc:test-type1* (zalloc)))
          (println mc)
          void
          )))
    
    (test-bad-print)
    ;; this will print

But if I restart the process, change void to i64 (or float, just not void) like:

    (bind-func test_print:[i64,test-type1*]*
      (lambda (x)
        (println "this will NOT print")
        1))

The "what is this" underscore gets printed, indicating that test_print is not getting called.

**Comment by digego** [comment]
The bind-poly is working ok, the bug is in the type system.  It is preferring the generic type selection [void,!a]* over poly'd [i64,test-type1*]*.
