### ISSUE TITLE
problem installing on osx

### ISSUE THREAD

**Issue by cancandan** [digego/extempore#220]
osx 10.9.5
brew install extempore result:

linking failed with exit code  13 
CMake Error at extras/cmake/aot.cmake:22 (message):
  Problem compiling libs/core/std.xtm

make[3]: *** [CMakeFiles/aot] Error 1
make[2]: *** [CMakeFiles/aot.dir/all] Error 2
make[1]: *** [CMakeFiles/aot.dir/rule] Error 2
make: *** [aot] Error 2

**Comment by benswift** [comment]
Hmm, never seen that one before.  Can you try again with --verbose flag
enabled (so brew doesn't suppress output) and attach the full log?

Cheers,
Ben

**Comment by cancandan** [comment]
Compiling native shared library 
   clang -O3 -dynamiclib -undefined dynamic_lookup /tmp/extempore/xtmstd.s -o /usr/local/Cellar/extempore/0.6.0/share/extempore/libs/aot-cache/xtmstd.dylib 

linking failed with exit code  13 
CMake Error at extras/cmake/aot.cmake:22 (message):
  Problem compiling libs/core/std.xtm


make[3]: *** [CMakeFiles/aot] Error 1
make[2]: *** [CMakeFiles/aot.dir/all] Error 2
make[1]: *** [CMakeFiles/aot.dir/rule] Error 2
make: *** [aot] Error 2
==> Formula
Tap: benswift/extempore
Path: /usr/local/Library/Taps/benswift/homebrew-extempore/extempore.rb
==> Configuration
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: d875c556f92df2bc88d987be16b685a40154d0e6
Last commit: 4 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: dual-core 64-bit penryn
OS X: 10.9.5-x86_64
Xcode: 6.1.1
CLT: 6.2.0.0.1.1424975374
Clang: 6.0 build 600
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.7.0_71, 1.6.0_65-b14-462
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j2
CMAKE_PREFIX_PATH: /usr/local/opt/extempore-llvm:/usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.9
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Library/ENV/4.3:/usr/local/opt/cmake/bin:/usr/local/opt/extempore-llvm/bin:/usr/bin:/bin:/usr/sbin:/sbin

Error: benswift/extempore/extempore 0.6.0 did not build

**Comment by benswift** [comment]
Ah, I see the problem.  From `INSTALL.md`:

If you're on OSX **10.9** or earlier, there's an incompatibility with
your version of clang and the LLVM 3.7.0 which Extempore uses.  For
the moment the easiest way around this is to download the old `0.5.9`
version of Extempore with

```
brew tap benswift/extempore
brew install extempore059
```

if you want the "extended" libs (e.g. graphics)

```
brew install extempore059 --with-extended
```

Cheers,
Ben

**Comment by benswift** [comment]
I'm guessing that using v 0.59 fixed this? Closing it for now.
