### ISSUE TITLE
Maximum runtime exceeded in impc:ti:bang-type?

### ISSUE THREAD

**Issue by mrmagooey** [digego/extempore#225]
The following function:

    (sys:load "libs/core/adt.xtm")
    (bind-func bind
      " "
      (lambda (p f)
        (lambda (inp)
          (let ((pl1 (p inp)) ;; returns a list
                (pl2 (map f pl1))) ;; returns a list of lists
            (flatten pl2)))))

Causes the maximum runtime exceeded error to occur. Printing the type that `impc:ti:bang-type?` is trying to print, something appears to be creating a very long type string which is potentially infinitely repeating. As with all generics issues this might be a #187 bug.

**Comment by digego** [comment]
this is just flatten taking a very long (too long in this case) time to type solve (i'm working on a fix for this).

also note that this example doesn't do what you think. I expect you mean this to be a generic function - in which case you *must* provide a full generic closure signature.
