### ISSUE TITLE
bind-type allows improperly formed tuples

### ISSUE THREAD

**Issue by jasonlevine** [digego/extempore#226]
I accidentally put a whitespace after a comma between two types in a tuple and here's what happened:

```(bind-type mytype <float, float,float,float>)```
terminal: DataType:  mytype >>> <float,
console: high

```(bind-val myvar mytype)```
terminal: SetValue:  myvar >>> mytype
console: #t

```(xtmX (tset! myvar 0 2.4))```
console: 2.400000

```(xtmX (tset! myvar 1 3.4))```
terminal: Syntax Error tuple index out of bounds: (tuple-set! myvar 1 3.400000)
console: #f

Seems to me that the compiler should either have rejected my improperly formed tuple, or ignored the whitespace.

**Comment by digego** [comment]
yes, this is a pain, unfortunately not super easy to fix at the moment :(  will put it on the list.

**Comment by JimKuhn** [comment]
I **may** have addressed this in 0e4bd610dd2067b7b2d18daa9c6ceb4f76cdec52 

@digego, If it's wrong or insufficient, please re-open and/or fix the right way :-)

**Comment by digego** [comment]
I haven't tried an example, but it looks, from the diff, that this fix will
work well for the bind-type case, and does address the issue as specified
(so happy for it to be closed).

Just as a future/FYI note - Unfortunately this kind of type parsing error
is pervasive (i.e. whitespace in types is currently a parsing error), and
is generally not being caught/managed.  We really need this kind of
checking in many different places, for many different types (closures,
arrays, vectors as well as tuples).  But that's a job(s) for another time.
