### ISSUE TITLE
Building on Ubuntu 14.04.3 fails

### ISSUE THREAD

**Issue by mrmagooey** [digego/extempore#231]
[100%] Building CXX object CMakeFiles/extempore.dir/src/UNIV.cpp.o
    Linking CXX executable extempore
    CMakeFiles/extempore.dir/src/EXTLLVM.cpp.o: In function `extemp::EXTLLVM::initLLVM()':
    EXTLLVM.cpp:(.text+0x5564): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::regex_iterator(__gnu_cxx::__normal_iterator<char const*, std::string>, __gnu_cxx::__normal_iterator<char const*, std::string>, std::basic_regex<char, std::regex_traits<char> > const&, std::bitset<11ul>)'
    EXTLLVM.cpp:(.text+0x556c): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::regex_iterator()'
    EXTLLVM.cpp:(.text+0x5577): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::regex_iterator(std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> > const&)'
    EXTLLVM.cpp:(.text+0x55a7): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator!=(std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> > const&)'
    EXTLLVM.cpp:(.text+0x55b7): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator*()'
    EXTLLVM.cpp:(.text+0x5791): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator++()'
    collect2: error: ld returned 1 exit status
    make[2]: *** [extempore] Error 1
    make[1]: *** [CMakeFiles/extempore.dir/all] Error 2
    make: *** [all] Error 2

g++ --version

    ➜  cmake-build git:(master) g++ --version
    g++ (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4
    Copyright (C) 2013 Free Software Foundation, Inc.

**Comment by munshkr** [comment]
So I had the same problem, and it seems LLVM needs gcc 4.9+. See this [thread](https://groups.google.com/forum/#!topic/extemporelang/hc1QZ6ppIO0). Also, [these steps](http://askubuntu.com/questions/466651/how-do-i-use-the-latest-gcc-4-9-on-ubuntu-14-04/581497#581497) worked for me.

**Comment by benswift** [comment]
Yep, that's right.  Like I said, I have a patch here which removes the
need for 4.9, but I haven't had the time to merge it in with the big
changes which landed last week.  Sorry about that. Will try and get it
up asap.

Cheers,
Ben

**Comment by munshkr** [comment]
@benswift Thank you! I've just tried it on a different computer (still Ubuntu 14.04) which had the same gcc 4.8.4 and I confirm it compiles without problems :) Still having [this issue](https://github.com/digego/extempore/issues/235#issuecomment-173868443) though, but I guess it's something else.

**Comment by benswift** [comment]
No worries mate.

**Comment by digego** [comment]
should now be fixed in head.
