### ISSUE TITLE
i8tof gives incorrect results past 127

### ISSUE THREAD

**Issue by jasonlevine** [digego/extempore#232]
i8tof gives correct results from 0 to 127.

 After 127, ```(i8tof 128)``` gives ```-128.0```, ```(i8tof 129)``` gives ```-127.0```, all the way to ```(i8tof 256)``` which gives ```0.0```.  Is it treating the topmost bit as the sign? Doesn't seem like the correct behaviour to me.

**Comment by digego** [comment]
i8 is signed (as are i16,i32 and i64).  you want to use (ui8tof 128).
