### ISSUE TITLE
Add jack build support for portaudio to extempore cmake

### ISSUE THREAD

**Issue by Arseniusz** [digego/extempore#236]
Extempore not working with jack in Linux. Looks like portaudio compiled without jack support.

**Comment by benswift** [comment]
Hey, sorry, I'm away from the office for the next few days and don't
have access to a Linux box.  Can you see if this patch for
`CMakeLists.txt` works for you?




@@ -4,6 +4,7 @@ option(MCJIT "use LLVM's MCJIT for codegen" ON)
 option(BOOST "use boost library" OFF)
 option(IN_TREE "use the Extempore source dir as EXT_SHARE_DIR - useful
 for developers" ON)
 option(ASIO "use the ASIO Portaudio backend" OFF)
+option(JACK "use the Jack Portaudio backend" OFF)
 option(DOWNLOAD_LLVM "download and build LLVM (patched for Extempore)"
 ON)
 option(PACKAGE "set up install targets for packaging" OFF)
 option(EXTENDED_DEPS "download & build deps for aot_extended" OFF)
@@ -158,7 +159,15 @@ elseif(UNIX AND NOT APPLE)
     PRIVATE -DPA_USE_ALSA)
   target_link_libraries(portaudio
     PRIVATE asound)
-
+  if(JACK)
+    # and maybe Jack as well
+    target_sources(portaudio
+      PRIVATE src/portaudio/src/hostapi/jack/pa_jack.c)
+    target_compile_definitions(portaudio
+      PRIVATE -DPA_USE_JACK)
+    target_link_libraries(portaudio
+      PRIVATE libjack)
+  endif()
 elseif(WIN32)
   # use everything except for ASIO on Windows by default, but you can
   # use asio with the cmake ASIO option (see below)

**Comment by benswift** [comment]
Just wondering if you'd had a chance to try out the jack build process with the above patch?
