### ISSUE TITLE
`make install` does not install anything into /usr/local/share/extempore

### ISSUE THREAD

**Issue by antoinevg** [digego/extempore#238]
## Problem

According to [INSTALL.md](https://github.com/digego/extempore/blob/master/INSTALL.md):

> `make install` will install extempore into `/usr/local/bin` and the rest of the files (the "Extempore share directory") into `/usr/local/share/extempore`

What actually happens is that only `/usr/local/bin/extempore` gets installed.

## Workaround

As a workaround I'm currently building extempore as follows and everything seems to be working:

    mkdir cmake-build && cd cmake-build && cmake ..
    make
    make aot
    make aot_extended
    make assets
    make install
    cd ..
    mkdir /usr/local/share/extempore
    cp -r assets runtime docs examples extras libs /usr/local/share/extempore

## Environment

* OSX 10.10
* Xcode 7.2.1
* cmake 3.4.1

**Comment by benswift** [comment]
Ah, that's a problem with the doco - it should only move the executable,
and use the rest of the files (e.g. libs, examples, etc.) from the
cloned source tree. I've updated it to be a bit clearer.

If you *do* want to install the full libs, examples, etc. into
`/usr/local/bin` then you can still do that with the `-DIN_TREE=OFF`
cmake option.

**Comment by antoinevg** [comment]
Ah okay, that makes sense now :-) Thank you for clearing that up Ben!

**Comment by benswift** [comment]
No worries mate.
