### ISSUE TITLE
Something committed on Feb 23 broke the Mac and Linux aot loading!

### ISSUE THREAD

**Issue by tjltjl** [digego/extempore#242]
I'm getting bus error when loading xtmbase. Checking out 8218d22 works.
Curiously, the aot compilation process goes ok and during the aot compilation, the previous aots get loaded properly.

Tried undoing just the --attr change but that didn't seem to help.

**Comment by tjltjl** [comment]
Same thing on linux! Current d9ebcd96576119c8e9222b55eae1da1151b84867 fails, whereas yesterday's 8218d2282c8cf83fa8dba8cf583a3d31016931db works.

**Comment by benswift** [comment]
sorry about that - I was trying to fix the Windows build and forgot to push up the ifdef guards for the other platforms
