### ISSUE TITLE
emacs extempore-mode: eldoc not working

### ISSUE THREAD

**Issue by heikkil** [digego/extempore#243]
I just installed extempore-mode and it immediately started complaining that function eldoc-beginning-of-sexp is not defined. The problem is in [one line](https://github.com/digego/extempore/blob/master/extras/extempore.el#L1195), only.

I found this: https://github.com/clojure-emacs/cider/issues/838 and the suggested fix, replacing it with code from an other package, worked:

    (unless (fboundp 'eldoc-beginning-of-sexp)
          (defalias 'eldoc-beginning-of-sexp 'elisp--beginning-of-sexp)))

However, the cider package maintainer had solved the problem by copying the old eldoc function into cider. There was no reason given, and the above code works, so I am happy with it. Both solutions are a bit hackish, so I'll leave it to maintainers to decide which one to choose.

**Comment by benswift** [comment]
Thanks for the heads up. I take it you're on Emacs 25? Seems like they
moved a bunch of things around.

Just to confirm, that second option (the defalias one) works fine for
you?

**Comment by heikkil** [comment]
I should have said it, yes, I am now running GNU Emacs 25.1.50.1 (x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F1605)) of 2016-01-28. I have not upgraded to the latest, yet.

Defalias code that I pasted in my comment above works fine for me.

**Comment by benswift** [comment]
Ok, cool.  Well I might use that fix then. Thanks.

**Comment by benswift** [comment]
Cool.  It's fixed in the [extempore-emacs-mode](https://github.com/extemporelang/extempore-emacs-mode/commit/4ffd822d598754dbfe01bbd2eaf14678321a124b) repo, so it'll just be a package upgrade away once MELPA re-indexes.
