### ISSUE TITLE
Weird tail call bug, test enclosed, this causes gui.xtm to fail

### ISSUE THREAD

**Issue by tjltjl** [digego/extempore#249]
Debugging #241 I first compared the assembly from the first compile and second compile and found them different. The difference was that the first compile seemed to be using tail call optimization and the second not.

I came up with the following xtmtest for this.

```
(xtmtest∴
  '(let ((i 0))
     (bind-func tail_opt_test2
                (lambda (n:i64 oa:float*)
                  (print (pref oa 0))
                  (print (pref oa 1))
                  (print (pref oa 2))
                  (print (pref oa 3))
                  (println 42)
                  (let ((a:float* (salloc 4)))
                    (pset! a 0 1.)
                    (pset! a 1 2.)
                    (pset! a 2 3.)
                    (pset! a 3 4.)
                    (if (= n 0)
                      (printf "tail opt test passed!\n")
                      (tail_opt_test2 (- n 1) a)
                      )
                    )(let ((a:float* (salloc 4)))
                    (pset! a 0 1.)
                    (pset! a 1 2.)
                    (pset! a 2 3.)
                    (pset! a 3 4.)
                    (if (= n 0)
                      (printf "tail opt test passed!\n")
                      (tail_opt_test2 (- n 1) a)
                      )
                    )))
     (bind-func tail_opt_test3 
                (lambda (n:i64)
                  (let ((a:float* (salloc 4)))
                    (pset! a 0 1.)
                    (pset! a 1 2.)
                    (pset! a 2 3.)
                    (pset! a 3 4.)
                    (tail_opt_test2 n a)))))
     (tail_opt_test3 1))∴
```

To see the problem, start extempore fresh (this is important! This only manifests itself on the first run!)

Output from first run is with the third printed line garbled (just like the gui widget stuff was):

```
Compiled:  tail_opt_test2 >>> [i32,i64,float*]*
Compiled:  tail_opt_test3 >>> [i32,i64]*
1.0000002.0000003.0000004.00000042
1.0000002.0000003.0000004.00000042
tail opt test passed!
tail opt test passed!
1.0000001.000000-0.0000000.00000042
tail opt test passed!
tail opt test passed!
result: correct 
```

but now, if you run the same block again, you get
```
xtmtest  tail_opt_test3 
Compiled:  tail_opt_test2 >>> [i32,i64,float*]*
Compiled:  tail_opt_test3 >>> [i32,i64]*
1.0000002.0000003.0000004.00000042
1.0000002.0000003.0000004.00000042
tail opt test passed!
tail opt test passed!
1.0000002.0000003.0000004.00000042
tail opt test passed!
tail opt test passed!
result: correct 
```

correctly.

**Comment by digego** [comment]
Well spotted!  It is indeed compiling with tail recursion on the first compile only - I'll have to investigate further.

Of course the bug here is not the corrupt data per se - salloc in a recursive call is an all bets off situation - the bug is that tail recursion is only being activated on the *first* compile.  i.e. the salloc code example should produce garbled output every-time - not just the first time it is compiled.

**Comment by tjltjl** [comment]
Ouch... that would definitely merit a warning or even an error since even gui.xtm does it and it is not obvious that this is what should be happening.

What would be the best way of writing that recursion (gui_render_subtree)? Because it does have a reasonable need for the stack-allocated things; it is able to only keep the current branch of the tree there.

A third alternative would be turning tail-call optimization off if you have a salloc in the function body...

I'm saying this because I didn't find a mention of this behaviour anywhere in the tutorials. They all talk about salloc being freed after the function returns but nothing about the recursion.

**Comment by digego** [comment]
Yes, as always documentation would be nice, and I agree that it's not
immediately obvious - particularly to anyone not familiar with tail
recursion.

Obviously it would be nice to have static alias checking, but at present we
do not.  A simple short term option, as you suggest, is to simply disable
tail recursion if *any* use of salloc is detected (regardless of context).
Obviously the down side to this naive approach is rejecting many valid use
cases.  Perhaps a printed warning is a sufficient compromise, although I'm
leaning towards the naive blanket approach.

One reason that I'm somewhat comfortable going with the warning approach is
that (z)alloc negates the problem - and is the general default case (or at
least should be).   Also, in general, a better approach for this type of
problem is using values - which is something that has admittedly not been
well supported in the past, and is still something that I'm playing around
with.

**Comment by benswift** [comment]
> One reason that I'm somewhat comfortable going with the warning approach is
> that (z)alloc negates the problem - and is the general default case (or at
> least should be).

Indeed - the gui.xtm library should be changed - I'll do that asap.
Thanks for the detective work.

**Comment by digego** [comment]
This is now fixed - in the sense that salloc will now crash *every* time ;)
