### ISSUE TITLE
‘jack_port_get_latency’ is deprecated

### ISSUE THREAD

**Issue by Arseniusz** [digego/extempore#251]
[ 48%] Building C object CMakeFiles/portaudio.dir/src/portaudio/src/hostapi/jack/pa_jack.c.o
/home/dude/extempore/src/portaudio/src/hostapi/jack/pa_jack.c: In function ‘BuildDeviceList’:
/home/dude/extempore/src/portaudio/src/hostapi/jack/pa_jack.c:598:17: warning: ‘jack_port_get_latency’ is deprecated [-Wdeprecated-declarations]
                 jack_port_get_latency( p ) / globalSampleRate;
                 ^
In file included from /home/dude/extempore/src/portaudio/src/hostapi/jack/pa_jack.c:63:0:
/usr/include/jack/jack.h:1226:16: note: declared here
 jack_nframes_t jack_port_get_latency (jack_port_t *port) JACK_OPTIONAL_WEAK_DEPRECATED_EXPORT;
                ^
/home/dude/extempore/src/portaudio/src/hostapi/jack/pa_jack.c:619:17: warning: ‘jack_port_get_latency’ is deprecated [-Wdeprecated-declarations]
                 jack_port_get_latency( p ) / globalSampleRate;
                 ^
In file included from /home/dude/extempore/src/portaudio/src/hostapi/jack/pa_jack.c:63:0:
/usr/include/jack/jack.h:1226:16: note: declared here
 jack_nframes_t jack_port_get_latency (jack_port_t *port) JACK_OPTIONAL_WEAK_DEPRECATED_EXPORT;
                ^
/home/dude/extempore/src/portaudio/src/hostapi/jack/pa_jack.c: In function ‘OpenStream’:
/home/dude/extempore/src/portaudio/src/hostapi/jack/pa_jack.c:1301:9: warning: ‘jack_port_get_latency’ is deprecated [-Wdeprecated-declarations]
         stream->streamRepresentation.streamInfo.inputLatency = (jack_port_get_latency( stream->remote_output_ports[0
         ^
In file included from /home/dude/extempore/src/portaudio/src/hostapi/jack/pa_jack.c:63:0:
/usr/include/jack/jack.h:1226:16: note: declared here
 jack_nframes_t jack_port_get_latency (jack_port_t *port) JACK_OPTIONAL_WEAK_DEPRECATED_EXPORT;
                ^
/home/dude/extempore/src/portaudio/src/hostapi/jack/pa_jack.c:1305:9: warning: ‘jack_port_get_latency’ is deprecated [-Wdeprecated-declarations]
         stream->streamRepresentation.streamInfo.outputLatency = (jack_port_get_latency( stream->remote_input_ports[0
         ^
In file included from /home/dude/extempore/src/portaudio/src/hostapi/jack/pa_jack.c:63:0:
/usr/include/jack/jack.h:1226:16: note: declared here
 jack_nframes_t jack_port_get_latency (jack_port_t *port) JACK_OPTIONAL_WEAK_DEPRECATED_EXPORT;
                ^
/home/dude/extempore/src/portaudio/src/hostapi/jack/pa_jack.c: In function ‘RealProcess’:
/home/dude/extempore/src/portaudio/src/hostapi/jack/pa_jack.c:1367:9: warning: ‘jack_port_get_latency’ is deprecated [-Wdeprecated-declarations]
         timeInfo.inputBufferAdcTime = timeInfo.currentTime - jack_port_get_latency( stream->remote_output_ports[0] )
         ^
In file included from /home/dude/extempore/src/portaudio/src/hostapi/jack/pa_jack.c:63:0:
/usr/include/jack/jack.h:1226:16: note: declared here
 jack_nframes_t jack_port_get_latency (jack_port_t *port) JACK_OPTIONAL_WEAK_DEPRECATED_EXPORT;
                ^
/home/dude/extempore/src/portaudio/src/hostapi/jack/pa_jack.c:1370:9: warning: ‘jack_port_get_latency’ is deprecated [-Wdeprecated-declarations]
         timeInfo.outputBufferDacTime = timeInfo.currentTime + jack_port_get_latency( stream->remote_input_ports[0] )
         ^
In file included from /home/dude/extempore/src/portaudio/src/hostapi/jack/pa_jack.c:63:0:
/usr/include/jack/jack.h:1226:16: note: declared here
 jack_nframes_t jack_port_get_latency (jack_port_t *port) JACK_OPTIONAL_WEAK_DEPRECATED_EXPORT;

**Comment by benswift** [comment]
Those deprecated calls are actually in PortAudio[0] (we just include the
files in the Extempore repo for convenience) so that's probably a better
place to raise this issue.

I'll close the issue here, but thanks for the heads up.

[0] http://www.portaudio.com/
