### ISSUE TITLE
CMake 3.5 now required (aot_extended)

### ISSUE THREAD

**Issue by JimKuhn** [digego/extempore#253]
Relatively minor, but annoying:

c939ed064b3ef84f5df701d49499671e29b04866 forces use of CMake 3.5 by passing multiple files to `cmake -E copy`. That's a new feature of 3.5.

As an aside, the library names for `libglfw` and `libapr-1` were incorrect on my (Ubuntu Wily) system.  For the built libraries, I have `libglfw.so` and `libapr-1.so` instead of the `libglfw.3.so` and `libapr-1.0.so` that the command was looking for.

**Comment by benswift** [comment]
Ah, bummer - I didn't realise that, that patch was a fix for another
issue in the "copy libs into place" step. I'll look into it.

Cheers
Ben
