### ISSUE TITLE
make aot twice compiles all files instead only files with changes.

### ISSUE THREAD

**Issue by neilt** [digego/extempore#258]
When running `make aot` twice all files are compiled instead of only compiling changed files.

Using git build with 7.0 rc1 tag.

**Comment by neilt** [comment]
Using git build with 7.0 rc1 tag.

**Comment by benswift** [comment]
Yep, that's a known issue, and I've tried a couple of things to fix it
with no luck. If anyone knows the magical cmake incantations to get it
to only re-aot changed files, I'd be very happy to give it another look.

One saving grace is that aot compilation is parallelizable on osx/linux,
so e.g. make -j4 might make your life easier.

Cheers
Ben

**Comment by benswift** [comment]
I guess this is a cantfix for now---I don't think it's possible with our current setup.  Happy to be proved wrong, though :)
