### ISSUE TITLE
'make install' on Linux failing during docs install

### ISSUE THREAD

**Issue by hackspanner** [digego/extempore#261]
'make install' fails during LLVM build of docs.

Specifically, lines 35-37 in the generated llvm/src/LLVM-build/docs/cmake_install.cmake refer to some non-existent ocaml docs for LLVM. Removing these lines allows the build to complete without errors.

Can't really make a pull request because of the internal LLVM build.

**Comment by benswift** [comment]
Hmm, that's weird. What Linux distro are you on?

We do have *some* control over how LLVM gets built - we can pass cmake
arguments to the LLVM configure process (see CMakeLists.txt:322). So if
we can find the right incantations to pass through we can possibly fix
it?

**Comment by hackspanner** [comment]
I'm on Debian 'stretch'. Yeah, it seems strange that just those lines for ocaml documentation show up. I do have OCaml installed, so that may be a factor.

**Comment by benswift** [comment]
Hmm, ok. Well, I must confess I've never really tried to build on a box
with OCaml installed.  That sucks if LLVM's build process is borked when
that's true.

As a sanity check, can you download and build LLVM 3.7 yourself, and see
if that works?

Cheers
Ben

**Comment by hackspanner** [comment]
Okay, I looked into this more and built extempore successfully on another machine with Debian stretch and OCaml. The problem is that on the original machine I had installed OCaml through the OCaml package manager (opam) instead of installing from Debian apt-get. LLVM seems to require something that's only part of the apt-get version. You should probably close this issue, since this is a problem with ocaml and llvm and not extempore.

**Comment by benswift** [comment]
Ok, great. Thanks for looking into it.  Closing #261.
