### ISSUE TITLE
echoed eval results (down TCP connection) don't seem to be getting flushed

### ISSUE THREAD

**Issue by benswift** [digego/extempore#266]
On OSX, upon connecting to extempore, one gets the usual "Welcome to Extempore!" message.  After that, successive messages (i.e. string representations of the expression's value) get glommed on to one another, e.g. "one"..."onetwo"..."onetwothree" etc.

**Comment by JimKuhn** [comment]
Fixed in 27c9657a4c6d12e0fe5a72d132ca64974fe36a43
