### ISSUE TITLE
audio inputs are broken

### ISSUE THREAD

**Issue by digego** [digego/extempore#269]
A reminder to self - audio inputs are broken (sometime since 0.7.0)

**Comment by JimKuhn** [comment]
Probably my fault.  I've never used them and did mess around in AudioDevice... I'll try to use inputs sometime in the next few days.

**Comment by digego** [comment]
No drama, I'll get around to it in the next week or so.

**Comment by JimKuhn** [comment]
Fixed (for single input channel at least) in: 3a0b70ecd4cb1a14b977ce2ae6e2fd2f1877fdbb
