### ISSUE TITLE
reduce the installation size

### ISSUE THREAD

**Issue by Wang-Yue** [digego/extempore#271]
Now the demo asset christmas_carol.aif is around 100M, and that's almost half of the total. Probably you can just replace it with a smaller sample.

**Comment by benswift** [comment]
Yep, fair enough.  I'll have a look at cutting it down.

**Comment by benswift** [comment]
since we've now got `ASSETS=ON/OFF` (`OFF` by default) as a build option in the CMake build
process, each user can opt in or out of dowloading the large-ish asset file. So
I think that's an acceptable compromise here, and I'll close this issue.
