### ISSUE TITLE
Xtlang callback pointer changes -- why is this happening?

### ISSUE THREAD

**Issue by jkroll20** [digego/extempore#275]
In the code below, the ```ptr``` argument changes each time ptr_callback is called.

```scheme
(bind-type mytype <i64,i64,i8>)
(bind-func ptr_callback
  (lambda (ptr:mytype* time:i64 dtime:float)
    (printf "ptr_callback ptr=%p\n" ptr)
    (let ((next_time (+ time (convert (* 44100. dtime)))))
      (callback next_time ptr_callback ptr next_time dtime))))
(xtmX (ptr_callback (halloc) (now) (/ 1.0 10.0)))
```

Sample output: 
```
ptr_callback ptr=0x7fc9d45c3e40
ptr_callback ptr=0x7fc9d4c543e0
ptr_callback ptr=0x7fc9d4bcf4e0
ptr_callback ptr=0x7fc9d4d6ee80
ptr_callback ptr=0x7fc9d4d42f60
ptr_callback ptr=0x7fc9d4cf7f80
ptr_callback ptr=0x7fc9d4d750c0
ptr_callback ptr=0x7fc9d4c44f00
ptr_callback ptr=0x7fc9d4c25480
ptr_callback ptr=0x7fc9d4d7a440
```

I don't understand why this is happening.

**Comment by benswift** [comment]
This is an interesting one - I should do a more in-depth blog post about it but the short answer is that `callback` performs a copy of the `MyType` tuple. This is necessary because otherwise there would be problems with passing types out of zones, etc.

Here's a working example: see that the pointer is changing, but the data is copied:

```
(bind-type MyType <i64,i64,i8>)

(bind-func ptr_callback
  (lambda (ptr:MyType* time:i64 dtime:float)
    (println ptr (cast ptr i8*))
    (let ((next_time (+ time (convert (* 44100. dtime)))))
      (callback next_time ptr_callback ptr next_time dtime))))

($ (ptr_callback (MyType 1 42 6) (now) 1.))
```

**Comment by JimKuhn** [comment]
I guess since ptr_callback can't know the allocation source (heap/zone/stack) it must copy (if the scope may no longer be valid) but that certainly does seem counter-intuitive.
