### ISSUE TITLE
vim editor docs error

### ISSUE THREAD

**Issue by MInner** [digego/extempore#291]
Hi,

one more little thing, in [docs](http://digego.github.io/extempore/editor-support.html#id7) you're saying that to connect to the thing, you have to do `<Leader>w` (`:ExtemporeSendEnclosingBlock`) even though from [sources](https://github.com/digego/extempore/blob/master/extras/extempore.vim#L60) it seems more like you should do `<Leader>o` (`:ExtemporeOpenConnection`) first.

And the latter thing is indeed required. That might lead to some confusion among beginners like me :)

**Comment by benswift** [comment]
Good catch as well - the `vim` docs (and the `vim` mode as well, really) could certainly be improved. Do you want to have a crack at making it better and submit a pull request? Contribute to the glorious forward march of open source and all that?

**Comment by MInner** [comment]
Sure, as soon as I have something to contribute. I'll keep spamming into your issue tracker for the time being, though, if you don't mind :) It doesn't seem like worth doing an entire pull request for a little docs change, or does it? If that is considered to be a right way of contributing small changes to docs (instead of opening issues here and there), then I can do that.

**Comment by benswift** [comment]
Acutally, I'm keen for small contributions as well - it's a "teach a man to fish" thing. So if you're willing, that's my preference :)

**Comment by digego** [comment]
did this go anywhere?

**Comment by benswift** [comment]
not sure. we can probably close
