### ISSUE TITLE
Issue building on Linux Mint 17 Qiana 64-bit

### ISSUE THREAD

**Issue by davidkneely** [digego/extempore#294]
Scanning dependencies of target portmidi
[ 14%] Building C object CMakeFiles/portmidi.dir/pm_common/portmidi.c.o
[ 28%] Building C object CMakeFiles/portmidi.dir/pm_common/pmutil.c.o
[ 42%] Building C object CMakeFiles/portmidi.dir/porttime/porttime.c.o
[ 57%] Building C object CMakeFiles/portmidi.dir/porttime/ptlinux.c.o
[ 71%] Building C object CMakeFiles/portmidi.dir/pm_linux/finddefault.c.o
[ 85%] Building C object CMakeFiles/portmidi.dir/pm_linux/pmlinux.c.o
[100%] Building C object CMakeFiles/portmidi.dir/pm_linux/pmlinuxalsa.c.o
**/home/david/code/extempore/cmake-build/portmidi/src/portmidi/pm_linux/pmlinuxalsa.c:19:28: fatal error: alsa/asoundlib.h: No such file or directory
 #include <alsa/asoundlib.h>**
                            ^
compilation terminated.
make[5]: *** [CMakeFiles/portmidi.dir/pm_linux/pmlinuxalsa.c.o] Error 1
make[4]: *** [CMakeFiles/portmidi.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [portmidi/src/portmidi-stamp/portmidi-build] Error 2
make[1]: *** [CMakeFiles/portmidi.dir/all] Error 2
make: *** [all] Error 2

**Comment by benswift** [comment]
Hi David

I don't have a mint box - so you might have to poke around in the package manager to find out which package provides the ALSA header files. Once we find the right package, I can add the info to the docs.

**Comment by digego** [comment]
Or David could update the docs with Mint instructions and submit a pull
request.

**Comment by jkroll20** [comment]
On Mint 18 (and most likely Mint 17), the package is called libasound2-dev.

`$ dpkg -S /usr/include/alsa/asoundlib.h 
libasound2-dev:amd64: /usr/include/alsa/asoundlib.h`

**Comment by benswift** [comment]
Cool, I've added the info in `9ff1bb32bf3a1b00a97c1519dd4c3d6dcf4909d0`
