### ISSUE TITLE
eval: unbound variable: bind-instrument

### ISSUE THREAD

**Issue by aarbarr** [digego/extempore#297]
I successfully cloned (github commit 1b761463e75750e978c97ff9b20ea123bd945eea) and built and ran (see details below) the client through Atom as per the instructions.  

I used the following command to build it:
```git clone https://github.com/digego/extempore && mkdir extempore/cmake-build && cd extempore/cmake-build && cmake .. && make install```

I am trying to run the following example: http://digego.github.io/extempore/time.html#scheduling-events-for-future-execution

But when I get to the second line of code:

```(bind-instrument synth synth_note_c synth_fx)```

, I get the following failure:

```eval: unbound variable: bind-instrument```

I'm sort of learning scheme/xtlang as I go along but it seems like the bind-instrument macro cannot be found.  I did a search in the code and I cannot find it either.  What am I missing?  Can you point me to the macro definition in the code?

```[aaron @ iron : ~/sandbox/music/archive/extempore] > extempore

------------- Extempore --------------
Andrew Sorensen (c) 2010-2016
andrew@moso.com.au, @digego

ARCH           : x86_64-apple-darwin16.6.0
CPU            : broadwell
ATTRS          : -sse4a,-avx512bw,+cx16,-tbm,+xsave,-fma4,-avx512vl,+prfchw,+bmi2,+adx,-xsavec,+fsgsbase,+avx,-avx512cd,-avx512pf,-rtm,+popcnt,+fma,+bmi,+aes,+rdrnd,-xsaves,+sse4.1,+sse4.2,+avx2,-avx512er,+sse,+lzcnt,+pclmul,-avx512f,+f16c,+ssse3,+mmx,-pku,+cmov,-xop,+rdseed,+movbe,-hle,+xsaveopt,-sha,+sse2,+sse3,-avx512dq
LLVM           : 3.8.0 MCJIT
Output Device  : Audioengine B1
Input Device   :
SampleRate     : 44100
Channels Out   : 2
Channels In    : 0
Frames         : 128
Latency        : 2.8642 sec

Primary on Thread 0
---------------------------------------

Starting utility process
Trying to connect to 'localhost' on port 7098
New Client Connection
Successfully connected to remote process

Starting primary process
Trying to connect to 'localhost' on port 7099
New Client Connection
Successfully connected to remote process
Loading xtmbase library... done in 4.217324 seconds
New Client Connection
Loading xtmmath library... done in 13.226667 seconds
Loading xtmaudiobuffer library... done in 3.271111 seconds
Loading xtmaudio_dsp library... done in 27.181859 seconds
Loading xtminstruments library... done in 8.016689 seconds
sys:load notification instruments already loaded
stack-catch: ()
stack-catch: ()
stack-catch: ()
eval: unbound variable: bind-instrument
Trace:
```

**Comment by digego** [comment]
Hi Aaron,

In short, you now need to use the make-instrument macro.  We changed the
instrument infrastructure a little while back and I'm afraid that the
documentation is woefully out of date.  The examples are up to date though
and my suggestion is that you start with examples/core/fmsynth.xtm.

Cheers,
Andrew.

**Comment by aarbarr** [comment]
Ok thank you.

**Comment by JTriggerFish** [comment]
I also cloned and built fine, setup atom etc but when trying to run fmsynth.xtm I'm getting:

------------- Extempore --------------
Andrew Sorensen (c) 2010-2016
andrew@moso.com.au, @digego

ARCH           : x86_64-pc-windows-msvc-elf
LLVM           : 3.8.0 MCJIT
Output Device  : ASIO4ALL v2
Input Device   :
SampleRate     : 48000
Channels Out   : 2
Channels In    : 0
Frames         : 128
Latency        : 0.01825 sec

Primary on Thread 0
---------------------------------------

Starting utility process
Trying to connect to 'localhost' on port 7098
New Client Connection
Successfully connected to remote process

Starting primary process
Trying to connect to 'localhost' on port 7099
New Client Connection
Successfully connected to remote process
Loading xtmbase library... done in 2.773333 seconds
New Client Connection
sys:load notification Error: xtlang code must be compiled in the primary process.
eval: unbound variable: make-instrument
Trace: sys:load

**Comment by digego** [comment]
Make sure you connect to the 'primary process' on port 7099.  It looks like
you've 'connected atom' to the utility process on 7098.

**Comment by JTriggerFish** [comment]
You were right, thank you for the quick response !
I think I had issues the first time and then assumed I was connecting to the wrong port and got confused.

Some library loading takes a bit of time I don't know if that's expected?

Primary on Thread 0
---------------------------------------

Starting utility process
Trying to connect to 'localhost' on port 7098
New Client Connection
Successfully connected to remote process

Starting primary process
Trying to connect to 'localhost' on port 7099
New Client Connection
Successfully connected to remote process
Loading xtmbase library... done in 3.026667 seconds
New Client Connection
Loading xtmrational library... done in 2.693333 seconds
Loading xtmaudiobuffer library... done in 2.013333 seconds
Loading xtmaudio_dsp library... done in 21.000000 seconds
Loading xtminstruments library... done in 10.466667 seconds
sys:load notification instruments already loaded
SetValue:  fmsynth >>> [float,float,i64,i64,float*]*
New instrument bound as fmsynth in both scheme and xtlang
Compiled:  dsp >>> [float,float,i64,i64,float*]*
zerolatency: #t

**Comment by digego** [comment]
yep, long load times are expected :(

This is something that I would *really* like to fix, but the fix isn't
straightforward so for the foreseeable future we're stuck with long load
times.  The good news, I guess, is that we will improve load times
significantly at some point in the future.

**Comment by digego** [comment]
Just FYI, if you're on windows you might like to give vscode a go.

**Comment by JTriggerFish** [comment]
Thank you ! Any particular reason ? I use both a bit for developing, I find each of them has different strengths

**Comment by digego** [comment]
The main reason is that I'm using vscode as my main extempore editor these
days.  Which simply means that the extempore mode on vscode is (arguably)
more likely to be up to date.

**Comment by benswift** [comment]
this should all be sorted now. the docs aren't perfect, but better than they
were - let us know if there are any bits which are still out-of-date.
