### ISSUE TITLE
Build hangs on OSX when compiling from master

### ISSUE THREAD

**Issue by cianoc** [digego/extempore#308]
When trying to compile on OSX from master the build process hangs when compiling the xtm files. I've attached a screenshot of where exactly this occurs in the build process.

I was trying to compile a package so that I could create a DMG file, but others have reported encountering the same problem.

![screen shot 2017-12-13 at 9 27 37 am](https://user-images.githubusercontent.com/355604/33944073-00a58fae-dfe9-11e7-83cd-cd53a33c5d48.png)

**Comment by cianoc** [comment]
Having looked into it there seems to be a permissions problem. When I gave up and cancelled it I got the message:
"cannot write AOT-compilation file at  ./libs/aot-cache/base.xtm"

When I looked at that directory I saw that the files in aot-cache have the permissions set to:
+ **user** - root
+ **group** - staff

Which doesn't seem right.

**Comment by benswift** [comment]
Just to follow-up, does it only happen when trying to re-build Extempore from an existing `cmake-build` directory which has already built Extempore in the past?

**Comment by benswift** [comment]
I'm having trouble reproducing - both building from "clean", and re-building works fine on my machine.

The other possibility is that the firewall is blocking Extempore from making connections to localhost? Do you get a bunch of these boxes popping up:

![screen shot 2017-12-14 at 1 29 35 pm](https://user-images.githubusercontent.com/380241/33972652-0cbd8d56-e0d3-11e7-9a44-3030f0fb221e.png)

**Comment by cianoc** [comment]
It’s definitely not the firewall and it was a clean build.

Are you in the staff group on your Mac? I wonder if that could be the difference.

**Comment by benswift** [comment]
hmm, yep, I am

```
uid=501(ben) gid=20(staff) groups=20(staff),12(everyone),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),701(1),33(_appstore),100(_lpoperator),204(_developer),250(_analyticsusers),395(com.apple.access_ftp),398(com.apple.access_screensharing),399(com.apple.access_ssh)
```
This was a clean install of 10.13 about 2 weeks ago, and I haven't played sillybuggers with the groups at all (except that I think homebrew might do some weird stuff)?

So yeah, that could well be the issue - the question is how to fix?

**Comment by cianoc** [comment]
No that's not it. That seems to be the default group on OSX. I just updated to High Sierra and nuked everything. Maybe that'll fix it.

**Comment by cianoc** [comment]
Ok that worked. No idea what was different. Still can't work out how to build a DMG though.

**Comment by benswift** [comment]
Ok. I've now downloaded XCode, I'll try the dmg thing again.
