### ISSUE TITLE
Recursion causes a segfault

### ISSUE THREAD

**Issue by cianoc** [digego/extempore#309]
```
(bind-func fact
  (lambda (n)
    (let ((p (- n 1)))
      (if (<= n 0) (1)
        (* n (fact p))))))
          

(bind-func fact3
  (lambda (n)
    (let ((total 1))
      (while (> n 0)
        (set! total (* total n))
        (set! n (- n 1)))
      (println total))))

```
Running ```($ (println (fact 1600000)))``` results in a segfault. In contrast running: ```(fact3 1600000)```
does not.

This would suggest that tail optimization isn't implemented for xtlang.

**Comment by digego** [comment]
Hey Cian,

;; not tail recursive
(bind-func fact1
  (lambda (n)
    (if (<= n 0) 
        1
        (* n (fact1 (- n 1))))))

;; tail recursive
(bind-func fact2
  (lambda (nn)
    (let ((f (lambda (n k)
              (if (<= n 0) 
                  k
                  (f (- n 1) (* (i64tod n) k))))))
      (f nn 1.0))))


From: cianoc
Sent: Tuesday, 2 January 2018 11:54 AM
To: digego/extempore
Cc: Subscribed
Subject: [digego/extempore] Recursion causes a segfault (#309)

`(bind-func fact
(lambda (n)
(let ((p (- n 1)))
(if (<= n 0) (1)
(* n (fact p))))))
(bind-func fact3
(lambda (n)
(let ((total 1))
(while (> n 0)
(set! total (* total n))
(set! n (- n 1)))
(println total))))
Running($ (println (fact 1600000)))results in a segfault. In contrast running:(fact3 1600000)`
does not.
This would suggest that tail optimization isn't implemented for xtlang.

**Comment by cianoc** [comment]
Ah gotcha. I shall document this as it's non-obvious. I will close this issue once I've got something written about it.
