### ISSUE TITLE
Docs: some suggestions

### ISSUE THREAD

**Issue by grav** [digego/extempore#327]
Hi! I actually started out with a PR to the docs, but it seems the html is auto-generated, and my phrasings aren't native-english anyway, so I'm just going to throw a couple of suggestions at you instead, as I go through the docs while learning extempore :-) 

I'm running Extempore 0.7.0, using a Macbook running OS X 10.12.6 and its built-in soundcard.

- In the examples in http://digego.github.io/extempore/time.html, add a note about how to stop the infinite sequence of callbacks, eg by re-defining `foo` to a `noop`.

- In first example, http://digego.github.io/extempore/audio-signal-processing.html, explain that the naming of the `dsp` function is arbitrary (but probably a convetion, I assume?) You're talking about a special function, `dsp`, but it seems that's not the case? It's only about the signature of the function.

- In same example, using a bit more precision on Pi (eg `3.14159`) avoids a periodic 'click' in the output.

- In the second example, same page, I needed to use`randomf` and not `random` (a lucky guess on my part!)

I'll add more as I progress :-)

**Comment by cyblue9** [comment]
Hi @grav !

Nice PR!😀
But, this docs(http://digego.github.io/extempore/) is outdated.
The new docs is https://extemporelang.github.io .

If you find some mistakes in docs, please send a PR to https://github.com/extemporelang/extemporelang.github.io repo !

**Comment by benswift** [comment]
Yep, thanks @cyblue9 - that's correct. 

@grav thanks for the suggestions - if you go to the [docs repo](https://github.com/extemporelang/extemporelang.github.io) then the content for the website is all there in markdown files, and those suggestions you make are good.

Perhaps you'd be willing to have a go at writing your suggestions up as a PR and then I'll review? Then you can get a merge requested and win the internet (I'm pretty that's how the internet works).

**Comment by benswift** [comment]
Ok, I think a bunch of these are fixed - I'll close for now, and we can just submit pull requests to the docs repo going forward (since that's the correct place for this issue anyway).
