### ISSUE TITLE
Which docs?

### ISSUE THREAD

**Issue by bradrn** [digego/extempore#328]
There seem to be two sets of docs: http://digego.github.io/extempore/index.html and https://extemporelang.github.io/docs/. Which one should I be using?

**Comment by benswift** [comment]
Hey @bradrn, sorry about the delayed reply - I'm currently on leave and not working on this stuff. But to answer your question, the extemporelang one is the current one ([source](https://github.com/extemporelang/extemporelang.github.io)).

I'll remove the old ones as soon as I'm back at work in a couple of weeks. Thanks for the heads up - we should do better with this.

**Comment by bradrn** [comment]
Thank you for clearing this up.
