### ISSUE TITLE
extempore/extras/.emacs file maybe wrong

### ISSUE THREAD

**Issue by blue-9** [digego/extempore#333]
I installed emacs(version 26.1) to play extempore.
I am a emacs beginner, So I referenced extempore/extras/.emacs (https://github.com/digego/extempore/blob/master/extras/.emacs)
to set .emacs.
When started up emacs, displayed following message.
```bash
error: Package ‘ido-ubiquitous-’ is unavailable
```

So, I fixed extempore/extras/.emacs 67 line as following.
```lisp
(dolist (package
         '(ido-completing-read+
```

As a result, I was able to start without any problem.

The same problem is occurring elsewhere.
(https://github.com/bbatsov/prelude/issues/1096)

Should I send a pull request?

**Comment by benswift** [comment]
Hey there, that "starter `.emacs`" is a real blast from the past - I haven't thought about it in a while.

A couple of thoughts:
1. yep, if it's broken, send a pull request (thanks)
2. if you don't have a dog in the "text editor" fight then VSCode is probably the better option these days unless you really want to take this opportunity to learn Emacs as well (if so, more power to you 🙂 )

**Comment by blue-9** [comment]
Thank to reply!

Oh I see.
I'm learning extempore from friend who is Emacser. So, I want to learn Emacs of this opportunity and I would like to refer to extempore/extras/.emacs.

Therefore,  I send a pull request!😀

**Comment by blue-9** [comment]
Thank you for the merge!
