### ISSUE TITLE
Proposal: Assign '(0 2 4 5 7 9 11) to variables

### ISSUE THREAD

**Issue by cyblue9** [digego/extempore#337]
I am learning extempore in the docs.

A lot of '(0 2 4 5 7 9 11) comes out in the chapter of Note-level music.

Therefore, I think that it would be better to assign '(0 2 4 5 7 9 11) to variables.

Example:(libs/core/pc_ivl.xtm)
```lisp
(define *pc:natural-note*
   '(0 2 4 5 7 9 11))
```

What do you think?

**Comment by benswift** [comment]
Well, that's just the pitch classes for the C major  ionian mode, and is already represented more generally as an interval list in the `*pc:scales*` variable.

So I don't think it's appropriate to put the hardcoded C-major version in the lib - the lib should be "key-agnostic" wherever possible.

However, perhaps we could better explain that list of magic numbers? What do you think?

**Comment by blue-9** [comment]
Oh, I see!
I understood that by reading to the source code of ```pc:scale``` function.
Thank you for explain😁!!!

Yes, I agree to explain ```*pc:scales*``` variable in the chapter of Note-level music of docs!
