### ISSUE TITLE
I want to display examples for each functions to understand easy.

### ISSUE THREAD

**Issue by blue-9** [digego/extempore#339]
Hi, @benswift !

I'm reading libs/core/pc_ivl.xtm to understand each pc: functions.

Examples of functions such as pc: relative are displayed in comments, but others are not displayed.
It is difficult to understand a function whose example is not displayed.

So, I am going to display examples of each function, can I send a pull request?

**Comment by benswift** [comment]
Sure, that'd be fine. In the comments is fine for the moment (just like all the others).

Thanks 😄
