### ISSUE TITLE
build broken on macOS/Linux due to libsndfile?

### ISSUE THREAD

**Issue by benswift** [digego/extempore#349]
I'm not sure if it's just that I'm in China, but I can no longer hit <http://www.mega-nerd.com/libsndfile/> and therefore the Extempore build is broken. Windows isn't affected, because we currently download a self-hosted binary for windows anyway.

I've actually pushed a fix which uses an updated version of libsndfile (on the `libsndfile-update` branch) which *should* finally work on Windows. But I haven't tested it there yet.

@digego have you build from scratch recently? Does libsndfile build ok on macOS/Linux?

**Comment by digego** [comment]
I'm windows only at the moment.

**Comment by doubleday** [comment]
FWIW: I just built on macOS 10.13 without any problems (master)

**Comment by benswift** [comment]
Yeah. It looked like the libsndfile download server was just unavailable for a while.
