### ISSUE TITLE
Project State

### ISSUE THREAD

**Issue by bradrn** [digego/extempore#356]
Do you have any idea what's happening with this project? The latest build is from 3 years ago, and it's been two months since the latest commit.

**Comment by digego** [comment]
It's moseying along at a leisurely pace :)  Important work is happening
though, and the project is most definitely "alive".

For some quite recent progress see:

https://www.youtube.com/watch?v=e1KI7eh8lAc

and

https://www.youtube.com/watch?v=ZxO-biTj3AI

These aren't "sexy", but they are important.

Cheers,
Andrew.

**Comment by bradrn** [comment]
Thanks! It's nice to see that this project is still alive - I've always found Extempore to be the nicest music livecoding language around. It would be nice to have those updates as a prebuilt executable though...

Also, what's happening with the documentation? Is it also being updated? Or will the next documentation update only be released with the next executable?

**Comment by benswift** [comment]
I should also add that updating the binary release infrastructure is on my to-do list, but I'm a latte papa at the moment (on parental leave) and really not having much time to look at this stuff. Too many nappies to change.

It *will* happen, but I can't give an eta right now. Thanks for the encouragement, though 😄

**Comment by bradrn** [comment]
Closing this, since it's resolved enough for my purposes.
