### ISSUE TITLE
syntactic sugar for aref, pref and tref?

### ISSUE THREAD

**Issue by digego** [digego/extempore#36]
thinking of adding `pptr[0]`, `aptr|0|` and `tptr<0>` for `pref` and `tref` indexing?  We could also think about `ptr[0]=` for `pref-set` etc..

we still need these to be unique at the moment to help out the type inferencer (i.e. we can't use `[]` for everything unfortunately).
this would be pure syntactic sugar at this stage - i.e. first-transform.

**Comment by benswift** [comment]
I guess if this has sat here for long enough, it's probably not a big deal.  Let's close it, and re-open it if it bugs us again.
