### ISSUE TITLE
analogue-load-preset isn't aware of the share dir

### ISSUE THREAD

**Issue by adql** [digego/extempore#373]
When trying to use `analogue-load-preset` to load a synth preset from `examples/sharedsystem/presets/` the result is an error opening the file (unless `extempore` was started at the share dir)

Steps to reproduce:
1. Start `extempore` anywhere out of the share dir.
2. Load the sharesystem: `(sys:load "examples/sharedsystem/setup.xtm")` – works fine (i.e. knows about Extempore's share dir)
3. Load a preset: `(analogue-load-preset syn1 "examples/sharedsystem/presets/blade1.xtmpreset")`. Result:

> Error opening file examples/sharedsystem/presets/blade1.xtmpreset

It's easy to workaround by starting Extempore at the share dir (or by using full path) but it's not very obvious (especially for new users) since `sys:load` _does_ succeed.

Build `e9daaa5` on Manjaro Linux.

**Comment by adql** [comment]
So simple... Thanks!

**Comment by benswift** [comment]
No worries mate :)
