### ISSUE TITLE
broken build on Windows Visual Studio 16 2019

### ISSUE THREAD

**Issue by benswift** [digego/extempore#376]
As our new testing infra has revealed, the build is broken on the latest VS (2019) - actually it's our old LLVM that's broken.

The fix is simple---need to add a `const` to LLVM's `utils/TableGen/AsmWriterEmitter.cpp:760` as indicated:

```cpp
//                                                          VVVVV         
bool operator()(const ValueType &LHS, const ValueType &RHS) const {
```

@digego I don't have ssh access to the `exempore.moso.au` server, can you modify that one file, re-xz the LLVM source and re-push it to the server? You'll have to calculate the md5 hash as well (and update it in `CMakeLists.txt` lines 315 and 339.

**Comment by benswift** [comment]
Actually, hang on... there are two more errors in `SLPVectorizer.cpp`. Will track them down now.

**Comment by benswift** [comment]
Ok, need to change this one in `lib/Transforms/Vectorize/SLPVectorizer.cpp:3088` as well:

```cpp
//                                                    VVVVV
bool operator()(ScheduleData *SD1, ScheduleData *SD2) const {
```

**Comment by digego** [comment]
done.

**Comment by benswift** [comment]
That's super---LLVM now builds on vs2019.

Sadly this just reveals that Extempote itself doesn't compile on vs2019 for a bunch of other reasons. I'll look into it asap.

**Comment by benswift** [comment]
Ok, this is now fixed. And the tests are all green, except... there's a catch. I'm just about to open another issue.
