### ISSUE TITLE
Mismatching MD5 for patched LLVM tarball

### ISSUE THREAD

**Issue by guygastineau** [digego/extempore#390]
I am trying to build it via NixOS, and #329  got me very far.
Currently the build process tries downloading `http://extempore.moso.com/extras/llvm-3.8.0.src-patched-for-extempore.tar.xz`, because it doesn't like the hash of the version I have locally in the repo.  The above file is downloaded, but make doesn't like the MD5 on the download either.  So i just keeps trying and increasing the retry timeout. 

I have tried while checking out master, while checking out `tags/v0.8.7`, and while checking out commit `4a6be4ef813a44d377a47de75bc8782c4f92a864` (which was used in the NixOS fix for #329, but I figured it was too out of date).

I followed the link for that file above, and I didn't even see the llvm version (I saw 3.7.x).  Is the proper file being kept somewhere else now?

Any help would be appreciated.  If I can get this to work, at least we can have up to date instructions for NixOS.  If I can get it working well, I will try to package it for NixOS, so there is official support with a new OS.

PS.  I tried installing this a few years ago through AUR on Arch, and somehow I was unlucky with sound configuration.  I love Scheme and studied composition at uni, so I am really excited to get this working on Nix.

**Comment by CastixGitHub** [comment]
```
$ ~  wget http://extempore.moso.com.au/extras/llvm-3.8.0.src-patched-for-extempore.tar.xz
--2020-07-29 20:20:49--  http://extempore.moso.com.au/extras/llvm-3.8.0.src-patched-for-extempore.tar.xz
Resolving extempore.moso.com.au (extempore.moso.com.au)... 66.175.214.198
Connecting to extempore.moso.com.au (extempore.moso.com.au)|66.175.214.198|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16573200 (16M) [application/x-xz]
Saving to: ‘llvm-3.8.0.src-patched-for-extempore.tar.xz’

llvm-3.8.0.src-patched-for-extempore 100%[=====================================================================>]  15.80M  1.72MB/s    in 9.5s     

2020-07-29 20:20:59 (1.66 MB/s) - ‘llvm-3.8.0.src-patched-for-extempore.tar.xz’ saved [16573200/16573200]

$ ~  md5sum llvm-3.8.0.src-patched-for-extempore.tar.xz 
600ee9a94d2e104f53be739568f3508e  llvm-3.8.0.src-patched-for-extempore.tar.xz
```

if you do md5sum of that file, is it the same? are you sure the download did't stop somehow?

**Comment by guygastineau** [comment]
Oh man, I forgot that I hard coded git to check out the commit hash from the fix in #329.  Sorry for the false alarm.

I guess I'll close this.  I just made it further, but I need to fiddle with the python packaging to get it working.  I'll create a PR (perhaps an issue first?) for documenting contemporary building with Nix package manager.

@CastixGitHub thank you for offering your help :bow:

**Comment by benswift** [comment]
Cool, thanks. I *am* open to PRs on the CMake build process (I hacked it together, but I'm sure a real CMake expert could improve it) and now that we've got cross-platform automated tests (with GH actions) it should be comparatively easy to make such changes with confidence.

**Comment by guygastineau** [comment]
I am somewhat comfortable with make, but I am very inexperienced with CMAKE. Sometimes this is unfortunate, but overall it probably leads to a more enjoyable life :/ lol

As far as I have made it now could be turned into a `.nix` file for making a nix shell that can build the project.  That information is useful for making a Nix package later, but it doesn't involve changes to the CMAKE file.  Although, I am running into issues regarding the copying of librtmidi, like the problem in #388, so maybe between us we can get the CMAKE working with Fedora and NixOS regarding that step!

**Comment by AleXoundOS** [comment]
@guygastineau, btw, maybe do you have a nix package/expression for extempore?

**Comment by guygastineau** [comment]
@AleXoundOS sadly no.  I left NixOS after they made breaking changes to the API invalidating my simple system config.  I have just gone back to Arch with pacman.  Good luck.

**Comment by akoppela** [comment]
@AleXoundOS Hi. I do have Nix package overlay for extempore. It’s for Darwin, but for Linux should be similar.

https://github.com/akoppela/.dotfiles/blob/master/nix/overlay/pkgs.nix#L4

**Comment by AleXoundOS** [comment]
@guygastineau, thank you for reply.
@akoppela, thank you very much!
