### ISSUE TITLE
cmake error: llvm tar download 404s 

### ISSUE THREAD

**Issue by fiskr** [digego/extempore#412]
Hello, I was following the instructions to build locally, in particular:

```
git clone https://github.com/digego/extempore && mkdir extempore/build && cd extempore/build && cmake -DASSETS=ON .. && make && sudo make install
```

On this step I get an error:

```
$ cmake -DASSETS=ON .. && make && sudo make install
-- Configuring done
-- Generating done
-- Build files have been written to: path/to/extempore/build
Consolidate compiler generated dependencies of target pcre
[  5%] Built target pcre
[ 12%] Built target portaudio_static
[ 13%] Performing download step (download, verify and extract) for 'LLVM'
-- verifying file...
       file='path/to/extempore/build/llvm/src/llvm-3.8.0.src-patched-for-extempore.tar.xz'
-- MD5 hash of
    path/to/extempore/build/llvm/src/llvm-3.8.0.src-patched-for-extempore.tar.xz
  does not match expected value
    expected: '600ee9a94d2e104f53be739568f3508e'
      actual: 'd41d8cd98f00b204e9800998ecf8427e'
-- File already exists but hash mismatch. Removing...
-- Downloading...
   dst='path/to/extempore/build/llvm/src/llvm-3.8.0.src-patched-for-extempore.tar.xz'
   timeout='none'
   inactivity timeout='none'
-- Using src='http://extempore.moso.com.au/extras/llvm-3.8.0.src-patched-for-extempore.tar.xz'
-- [download 0% complete]
CMake Error at LLVM-stamp/download-LLVM.cmake:170 (message):
  Each download failed!

    error: downloading 'http://extempore.moso.com.au/extras/llvm-3.8.0.src-patched-for-extempore.tar.xz' failed
          status_code: 22
          status_string: "HTTP response code said error"
          log:
          --- LOG BEGIN ---
            Trying 66.175.214.198:80...

  Connected to extempore.moso.com.au (66.175.214.198) port 80 (#0)

  GET /extras/llvm-3.8.0.src-patched-for-extempore.tar.xz HTTP/1.1

  Host: extempore.moso.com.au

  User-Agent: curl/7.80.0

  Accept: */*

  

  Mark bundle as not supporting multiuse

  HTTP/1.1 404 Not Found

  Date: Fri, 16 Feb 2024 21:15:03 GMT

  Server: Apache/2.4.29 (Ubuntu)

  Content-Length: 283

  Content-Type: text/html; charset=iso-8859-1

  The requested URL returned error: 404

  Closing connection 0

  

          --- LOG END ---
```

When I check the URL in the browser I confirm I see a 404. Any suggestions on how to move forward?

This is on Ubuntu 22.04, by the way. 

Thanks!

**Comment by garlic0x1** [comment]
I also am not able to connect to `extempore.moso.com.au`

**Comment by digego** [comment]
This is an issue. I'll have to get back to you on a resolution.  Hopefully
sometime next week.

Cheers,
Andrew

**Comment by garlic0x1** [comment]
Any update? I really want to try this.

**Comment by digego** [comment]
Ok, you should be good to go.  I've successfully compiled and run on linux
with a minimal build (no external libraries):

cmake ../ -DASSETS=OFF -DEXTERNAL_SHLIBS_AUDIO=OFF
-DEXTERNAL_SHLIBS_GRAPHICS=OFF && make

Note that extempore still only supports x86.  Also almost certainly have
trouble with EXTERNAL_SHLIBS_GRAPHICS so only give that a go if (a) you're
on linux or windows (def not osx) and (b) you're brave :)

There are no assets available at the moment, but if you're keen I can track
them down for you.

Cheers,
Andrew.

**Comment by juanmeleiro** [comment]
This still doesn't work for me. On a fresh clone, even on the latest release tag, it gives the same error. Is there some way to disable building LLVM?

**Comment by digego** [comment]
Try from head, not from a release tag.

**Comment by juanmeleiro** [comment]
Andrew Sorensen [2024-08-22 14:12]:
> Try from head, not from a release tag.


Well, it works, by then I get the following:

```
extempore/build/llvm/src/LLVM/lib/Support/DynamicLibrary.cpp:141:42: error: invalid conversion from 'const void*' to 'void*' [-fpermissive]
  141 |    if (!strcmp(symbolName, #SYM)) return &SYM
      |                                          ^
      |                                          |
      |                                          const void*
```

Should I open another issue?

-- 
Juan

**Comment by digego** [comment]
Go for it.  Make sure you include lots of details, like your OS version,
compiler type and version etc..  Just be aware that you may not get a fast
response to your issue.  Feel free to submit a PR.
