### ISSUE TITLE
Using extempore.vim: "SyntaxError: unexpected EOF while parsing"

### ISSUE THREAD

**Issue by rahji** [digego/extempore#75]
Trying the \o mapping with extempore.vim gives me this error:

  File "<string>", line 1
    open()^M
         ^
SyntaxError: unexpected EOF while parsing

All of the other commands give similar errors.  After removing the "<CR>" from the end of each line that starts with "command!" all of the commands work properly.

**Comment by digego** [comment]
anyone know where this is at?

**Comment by benswift** [comment]
Looks like this was merged in `3925908`.
