### ISSUE TITLE
Scheme case example that provides wrong answer and no syntax error.

### ISSUE THREAD

**Issue by neilt** [digego/extempore#99]
Not sure if this is good or bad syntax but the following provides the wrong answer and no syntax error.
```Scheme
(define test-case
  (lambda (arg1)
    (case arg1 (1 (print "A"))
	  (2 (print "B"))
	  (3 (print "C")))))
(test-case 2)
```
It prints A instead of B.  It works correctly if the numbers 1, 2, and 3 are enclosed in parenthesis.

**Comment by mrmagooey** [comment]
Tiny scheme adheres to the R5RS spec, and this is in line with that.

That `A` gets printed is a side effect of the case argument only evaluating the first malformed clause.

**Comment by digego** [comment]
added a syntax error for clarity. can you check for me Pete and close if happy.

**Comment by mrmagooey** [comment]
Looks good, just to be difficult though can I suggest we use the first part:

    Syntax Error: Case clause must have the form ((<datum1> ...) <exp1> <exp2> ...) 

Just to make the error a bit more general.

I don't have access rights on this repository, so I can't close any of the issues I've highlighted.

**Comment by digego** [comment]
Thanks, an OK in the comments is fine.

Not quite sure what you mean by "the first part"?  if you mean drop the
part following "not" then that is context dependent.
